---
- name: Breloque project playbook
  hosts: breloque
  remote_user: "{{ lookup('env', 'USER') }}"

  roles:
    - tmux
    - git
    - neovim
    - crush
    - nerdfonts
    - role: golang
      vars:
        go_version: "1.26.4"
