---
- name: i3wm config
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Ensure alacritty and dependencies are at the latest version
      dnf:
        name:
          - alacritty
          - tmux
        state: present
      become: yes

    - name: Symlink configurations
      file:
        src: "{{ ansible_env['PWD'] }}/files/terminal/{{ item.src }}"
        dest: "{{ item.dest }}"
        force: true
        state: link
      loop:
        - { src: "alacritty", dest: "~/.config/alacritty" }
        - { src: "_tmux.conf", dest: "~/.tmux.conf" }

