[colors.bright]
black = "#6e6e6e"
blue = "#007acc"
cyan = "#1aa893"
green = "#6b8900"
magenta = "#d33682"
red = "#dc322f"
white = "#434c5e"
yellow = "#b58900"

[colors.normal]
black = "#757575"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#191C24"
yellow = "#ebcb8b"

[colors.primary]
background = "#2e3440"
foreground = "#fcfcfc"

[colors.cursor]
text = "#2e3440"
cursor = "#fcfcfc"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "MonaspiceArNerdFontMono"
style = "Regular"
