---
- name: Install package
  package:
    name: emacs
    state: present
  become: true

- name: Create .bashrc.d directory
  ansible.builtin.file:
    path: ~/.bashrc.d
    state: directory

- name: Create .emacs.d directory
  ansible.builtin.file:
    path: ~/.emacs.d
    state: directory

- name: Create symlinks
  file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop: "{{ app_file_symlinks }}"
