---
- name: Ensure tmux and dependencies are at the latest version
  dnf:
    name:
      - tmux
    state: present
  become: yes

- name: Symlink configurations
  file:
    src: "{{ role_path }}/files/{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
    state: link
  loop:
    - { src: "_tmux.conf", dest: "~/.tmux.conf" }

