---
- name: Install package
  package:
    name: neovim,luarocks
    state: present
  become: true

- name: Clone neovim config
  git:
    repo: https://github.com/Ureakim/dotvim.git
    dest: $HOME/.config/nvim
    single_branch: yes
    version: nvim
